import { test, expect, type Page } from '@playwright/test'

async function ready(page: Page, base = '') {
  await page.goto(base + '/#/new')
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
}
async function send(page: Page, input: string) {
  await page.getByRole('textbox', { name: 'Message your agent…', exact: true }).fill(input)
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page).toHaveURL(/#\/sessions\//)
}
async function selectAnswerText(page: Page, passage: string) {
  const answer = page.locator('.message-assistant[data-message-index] .markdown').last()
  await expect(answer).toContainText(passage)
  await answer.evaluate((element, text) => {
    const node = element.querySelector('p')!.firstChild!
    const start = node.textContent!.indexOf(text)
    const range = document.createRange()
    range.setStart(node, start)
    range.setEnd(node, start + text.length)
    window.getSelection()!.removeAllRanges()
    window.getSelection()!.addRange(range)
    element.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }))
  }, passage)
}
async function clickHighlightedText(page: Page, passage: string) {
  const rect = await page.locator('.message-assistant[data-message-index] .markdown').last().evaluate((element, text) => {
    const node = element.querySelector('p')!.firstChild!
    const start = node.textContent!.indexOf(text)
    const range = document.createRange()
    range.setStart(node, start)
    range.setEnd(node, start + text.length)
    const box = range.getBoundingClientRect()
    return { x: box.left + box.width / 2, y: box.top + box.height / 2 }
  }, passage)
  await page.mouse.click(rect.x, rect.y)
}
async function openOperationDebugger(page: Page) {
  await page.goto('/#/operations')
  await expect(page.getByLabel('Select an operation')).toBeVisible()
}

test('workspace picker receives directory paths instead of the default label', async ({ page }) => {
  const response = await page.request.get('/api/state')
  expect(response.ok()).toBe(true)
  const snapshot = await response.json()
  const defaultPath: string = snapshot.workspace.defaultPath
  expect(defaultPath).not.toBe('')
  const customPath = defaultPath + '/selected workspace'
  const selections = [{ path: defaultPath }, { path: customPath }, {}]
  const initialPaths: string[] = []
  await page.route('**/api/workspace/select', async route => {
    initialPaths.push(route.request().postDataJSON().initialPath)
    await route.fulfill({ json: selections[initialPaths.length - 1] })
  })
  await ready(page)
  const picker = page.getByRole('button', { name: 'Choose workspace folder', exact: true })
  const chosen = page.locator('.workspace-chosen')

  await picker.click()
  await expect.poll(() => initialPaths).toEqual([defaultPath])
  await expect(chosen).toHaveText('default workspace')
  await expect(picker).toBeEnabled()

  await picker.click()
  await expect.poll(() => initialPaths).toEqual([defaultPath, defaultPath])
  await expect(chosen).toHaveText(customPath)
  await expect(picker).toBeEnabled()

  await picker.click()
  await expect.poll(() => initialPaths).toEqual([defaultPath, defaultPath, customPath])
  await expect(chosen).toHaveText(customPath)
  await expect(picker).toBeEnabled()
})

test('model and reasoning controls follow the selected provider', async ({ page }) => {
  await ready(page)
  const trigger = page.getByRole('button', { name: 'Model selection' })
  await expect(trigger).toContainText('chat')
  await expect(trigger).toContainText('low')
  await trigger.click()
  await page.getByRole('combobox', { name: 'Provider' }).selectOption('secondary')
  const models = page.getByRole('combobox', { name: 'Model', exact: true })
  await expect(models.locator('option')).toHaveCount(1)
  await expect(models.locator('option')).toHaveText('reasoner')
  await page.getByRole('combobox', { name: 'Reasoning effort' }).selectOption('high')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(trigger).toContainText('reasoner')
  await expect(trigger).toContainText('high')
  await trigger.click()
  await page.getByRole('combobox', { name: 'Reasoning effort' }).selectOption('providerDefault')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(trigger).toContainText('Provider default')
  await page.reload()
  await expect(trigger).toContainText('reasoner')
  await expect(trigger).toContainText('Provider default')
  await page.setViewportSize({ width: 390, height: 740 })
  await trigger.click()
  await expect(page.getByRole('combobox', { name: 'Provider' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('conversation creation, streamed output, usage sidebar, and history refresh', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await ready(page)
  await send(page, 'hello workspace')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  const card = page.locator('.session-usage-card')
  await expect(card.getByTestId('session-total')).toHaveText('72')
  await expect(card.getByTestId('context-total')).toHaveText('64')
  await expect(page.locator('.execution-panel > *')).toHaveCount(1)
  await expect(card.locator('.usage-metrics > div')).toHaveCount(2)
  await expect(page.locator('.execution-panel').getByText('Model calls', { exact: true })).toHaveCount(0)
  await expect(card.getByText('Latest request input', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Input tokens', { exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.message-user .message-content')).toHaveText('hello workspace')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await expect(card.getByTestId('session-total')).toHaveText('72')
  await expect(card.getByTestId('context-total')).toHaveText('64')
  await expect(page.locator('.execution-panel details, .execution-panel table')).toHaveCount(0)
  await send(page, 'continue the workspace')
  await expect(card.getByTestId('session-total')).toHaveText('144')
  await expect(card.getByTestId('context-total')).toHaveText('192')
  await expect(page.locator('.execution-panel > *')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/session-usage-desktop.png' })
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 740 })
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await expect(card.getByTestId('session-total')).toHaveText('144')
  await expect(card.getByTestId('context-total')).toHaveText('192')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-results/session-usage-mobile.png', animations: 'disabled' })
  expect(errors).toEqual([])
})

test('sidebar usage card shows only session and context totals in dark Chinese and mobile views', async ({ page }) => {
  await ready(page)
  await send(page, 'first usage check')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await send(page, 'second usage check')
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  const card = page.locator('.session-usage-card')
  await expect(card.getByTestId('session-total')).toHaveText('144')
  await expect(card.getByTestId('context-total')).toHaveText('192')
  await expect(card.locator('.usage-metrics > div')).toHaveCount(2)
  await expect(page.locator('.execution-panel details, .execution-panel table')).toHaveCount(0)
  await expect(card.getByText('Latest request input', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/usage-card-desktop.png', animations: 'disabled' })
  await page.evaluate(() => { localStorage.setItem('ingot.language', 'zh'); localStorage.setItem('ingot.theme', 'dark') })
  await page.reload()
  await expect(card.getByRole('heading', { name: 'Token 用量', exact: true })).toBeVisible()
  await expect(card.getByTestId('session-total')).toHaveText('144')
  await expect(card.getByTestId('context-total')).toHaveText('192')
  await expect(card.getByText('最近一次请求输入', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/usage-card-dark-desktop.png', animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 740 })
  await expect(page.getByRole('dialog', { name: '执行详情', exact: true })).toBeVisible()
  await expect(card.getByTestId('session-total')).toHaveText('144')
  await expect(card.getByTestId('context-total')).toHaveText('192')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-results/usage-card-dark-mobile.png', animations: 'disabled' })
})

test('selected answer opens a persistent independent follow-up', async ({ page }) => {
  await ready(page)
  await send(page, 'hello workspace')
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await selectAnswerText(page, 'workspace is ready')
  await page.getByRole('button', { name: 'Follow up', exact: true }).click()
  const note = page.getByRole('dialog', { name: 'Follow up' })
  await expect(note.getByText('workspace is ready', { exact: true })).toBeVisible()
  await expect(note.locator('.session-usage')).toHaveCount(0)
  await note.getByRole('textbox', { name: 'Ask about this passage…' }).fill('What does ready mean?')
  await note.getByRole('button', { name: 'Send message' }).click()
  await expect(note.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  await expect(note.locator('.session-usage')).toHaveCount(0)
  await expect(page.locator('.session-usage-card').getByTestId('session-total')).toHaveText('144')
  const inherited = await page.evaluate(async () => {
    const source = location.hash.split('/').pop()!
    const [item] = await (await fetch(`/api/sessions/${source}/followups`)).json()
    const history = await (await fetch(`/api/sessions/${item.id}/history`)).json()
    return { count: item.baseMessageCount, first: history[0].content[0].text, second: history[1].content[0].text }
  })
  expect(inherited.count).toBe(2)
  expect(inherited.first).toBe('hello workspace')
  expect(inherited.second).toContain('Your workspace is ready')
  await expect(page.locator('.transcript .message-user')).toHaveCount(1)
  await note.getByRole('button', { name: 'Close' }).click()
  await expect(note).toHaveCount(0)
  await expect(page.locator('.followup-pin')).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
  await clickHighlightedText(page, 'workspace is ready')
  await expect(page.getByRole('dialog', { name: 'Follow up' }).getByText('What does ready mean?', { exact: false })).toBeVisible()
  await expect(note.locator('.session-usage')).toHaveCount(0)
  await expect(page.locator('.session-usage-card').getByTestId('session-total')).toHaveText('144')
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 740 })
  await expect.poll(async () => {
    const bounds = await note.boundingBox()
    return bounds && bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y + bounds.height <= 740
  }).toBe(true)
  await page.screenshot({ path: 'test-results/session-usage-followup-mobile.png' })
  await page.getByRole('dialog', { name: 'Follow up' }).getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('dialog', { name: 'Follow up' }).getByRole('button', { name: 'Delete' }).last().click()
  await expect(note).toHaveCount(0)
  await clickHighlightedText(page, 'workspace is ready')
  await expect(note).toHaveCount(0)
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await expect(page.locator('.session-usage-card').getByTestId('session-total')).toHaveText('144')
})

test('a closed unsent note reopens with its draft and its floating window stays in the viewport', async ({ page }) => {
  await ready(page)
  await send(page, 'hello workspace')
  await selectAnswerText(page, 'workspace is ready')
  await page.getByRole('button', { name: 'Follow up', exact: true }).click()
  const note = page.getByRole('dialog', { name: 'Follow up' })
  await note.getByRole('textbox', { name: 'Ask about this passage…' }).fill('An unsent question')
  const before = await note.boundingBox()
  const grip = await page.getByRole('button', { name: 'Resize follow-up window' }).boundingBox()
  await page.mouse.move(grip!.x + grip!.width / 2, grip!.y + grip!.height / 2)
  await page.mouse.down()
  await page.mouse.move(grip!.x + 90, grip!.y + 75, { steps: 5 })
  await page.mouse.up()
  const expanded = await note.boundingBox()
  expect(expanded!.width).toBeGreaterThan(before!.width + 65)
  expect(expanded!.height).toBeGreaterThan(before!.height + 50)
  const compactGrip = await page.getByRole('button', { name: 'Resize follow-up window' }).boundingBox()
  await page.mouse.move(compactGrip!.x + compactGrip!.width / 2, compactGrip!.y + compactGrip!.height / 2)
  await page.mouse.down()
  await page.mouse.move(compactGrip!.x - 180, compactGrip!.y - 200, { steps: 5 })
  await page.mouse.up()
  expect((await note.boundingBox())!.height).toBeLessThan(expanded!.height - 100)
  await expect(note.getByRole('textbox', { name: 'Ask about this passage…' })).toBeVisible()
  const compact = await note.boundingBox()
  expect(compact!.width).toBeGreaterThanOrEqual(300)
  expect(await note.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await note.getByRole('button', { name: 'Close' }).click()
  await clickHighlightedText(page, 'workspace is ready')
  await expect(note.getByRole('textbox', { name: 'Ask about this passage…' })).toHaveValue('An unsent question')
  await page.reload()
  await clickHighlightedText(page, 'workspace is ready')
  await expect(note.getByRole('textbox', { name: 'Ask about this passage…' })).toHaveValue('An unsent question')
  await page.setViewportSize({ width: 1024, height: 768 })
  await expect(page.locator('.chat-main')).toBeVisible()
  await page.setViewportSize({ width: 758, height: 900 })
  const singleLine = note.getByRole('textbox', { name: 'Ask about this passage…' })
  expect((await singleLine.boundingBox())!.height).toBeLessThanOrEqual(32)
  expect(await singleLine.evaluate(element => getComputedStyle(element).resize)).toBe('none')
  await page.setViewportSize({ width: 390, height: 740 })
  await expect(page.locator('.chat-main')).toBeVisible()
  await expect.poll(async () => {
    const mobile = await note.boundingBox()
    return mobile && mobile.x >= 0 && mobile.x + mobile.width <= 390 && mobile.y + mobile.height <= 740
  }).toBe(true)
  const field = note.getByRole('textbox', { name: 'Ask about this passage…' })
  await expect(field).toHaveAttribute('rows', '1')
  const initialHeight = (await field.boundingBox())!.height
  await field.fill('First line\nSecond line\nThird line')
  expect((await field.boundingBox())!.height).toBeGreaterThan(initialHeight + 25)
  expect(await field.evaluate(element => getComputedStyle(element).resize)).toBe('none')
  await note.getByRole('button', { name: 'Close' }).click()
  await expect(page.locator('.chat-main')).toBeVisible()
  await clickHighlightedText(page, 'workspace is ready')
  await expect(note.getByRole('textbox', { name: 'Ask about this passage…' })).toHaveValue('First line\nSecond line\nThird line')
})

test('multiple follow-up windows can overlap and clicking a window brings it to the front', async ({ page }) => {
  await ready(page)
  await send(page, 'hello workspace')
  for (const passage of ['workspace is ready', 'next step together']) {
    await selectAnswerText(page, passage)
    await page.getByRole('button', { name: 'Follow up', exact: true }).click()
    await page.getByRole('dialog', { name: 'Follow up' }).getByRole('button', { name: 'Close' }).click()
  }
  const notes = await page.evaluate(async () => {
    const source = location.hash.split('/').pop()!
    return await (await fetch(`/api/sessions/${source}/followups`)).json() as { id: string; quote: string }[]
  })
  expect(notes).toHaveLength(2)
  await clickHighlightedText(page, 'workspace is ready')
  const first = page.locator(`.followup-window[data-note-id="${notes.find(note => note.quote === 'workspace is ready')!.id}"]`)
  const initial = await first.boundingBox()
  await page.mouse.move(initial!.x + 90, initial!.y + 22)
  await page.mouse.down()
  await page.mouse.move(110, 85, { steps: 5 })
  await page.mouse.up()
  await clickHighlightedText(page, 'next step together')
  const second = page.locator(`.followup-window[data-note-id="${notes.find(note => note.quote === 'next step together')!.id}"]`)
  await expect(page.getByRole('dialog', { name: 'Follow up' })).toHaveCount(2)
  const one = await first.boundingBox()
  const two = await second.boundingBox()
  await page.mouse.move(one!.x + 90, one!.y + 22)
  await page.mouse.down()
  await page.mouse.move(two!.x + 140, two!.y + 72, { steps: 8 })
  await page.mouse.up()
  const front = async () => page.evaluate(({ x, y }) => document.elementFromPoint(x, y)?.closest<HTMLElement>('.followup-window')?.dataset.noteId,
    { x: two!.x + 120, y: two!.y + 95 })
  expect(await front()).toBe(notes.find(note => note.quote === 'workspace is ready')!.id)
  await page.mouse.click(two!.x + 25, two!.y + 20)
  expect(await front()).toBe(notes.find(note => note.quote === 'next step together')!.id)
})

test('pending approval survives refresh while history is blocked and settles across tabs', async ({ page, context }) => {
  await ready(page)
  await send(page, 'approve workspace')
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(page.getByText('Earlier messages may be available after the current execution finishes.', { exact: true })).toBeVisible()
  const second = await context.newPage()
  await second.goto(page.url())
  await expect(second.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(second.getByText('Allow workspace inspection?', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await second.close()
})

test('free text answers can differ from suggestions', async ({ page }) => {
  await ready(page)
  await send(page, 'ask workspace')
  await page.getByRole('textbox', { name: 'Answer', exact: true }).fill('a different answer')
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
})

test('multi-round reasoning, commentary, tools and interactions append in order', async ({ page }) => {
  await ready(page)
  await send(page, 'timeline approve')
  const timeline = page.locator('.turn-content')
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(timeline.locator(':scope > *')).toHaveClass(['reasoning-block', 'markdown', 'tool-card', 'interaction-card', 'thinking-dots'])
  await timeline.locator('.reasoning-block summary').click()
  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Continue with verification?', { exact: true })).toBeVisible()
  await expect(timeline.locator(':scope > *')).toHaveClass(['reasoning-block', 'markdown', 'tool-card', 'reasoning-block', 'markdown', 'tool-card', 'interaction-card', 'thinking-dots'])
  await expect(timeline.locator('.reasoning-block').first()).toHaveAttribute('open', '')
  await expect(timeline.locator('.reasoning-block .markdown').first()).toHaveText('Checking the request.')
  await timeline.locator('.reasoning-block summary').nth(1).click()
  await expect(timeline.locator('.reasoning-block .markdown').nth(1)).toHaveText('Reviewing the inspection. Planning a verification.')
  await timeline.getByRole('textbox', { name: 'Answer', exact: true }).fill('Continue')
  await timeline.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  const history = page.locator('.transcript .message-assistant .message-content > .markdown, .transcript .tool-summary .font-mono')
  await expect(history).toHaveText(["I'll inspect the workspace first.", 'workspace.inspect', "The first check is complete. I'll verify the result.", 'workspace.verify', 'Your workspace is ready. We can take the next step together.'])
  await page.reload()
  await expect(history).toHaveText(["I'll inspect the workspace first.", 'workspace.inspect', "The first check is complete. I'll verify the result.", 'workspace.verify', 'Your workspace is ready. We can take the next step together.'])
})

test('tool call visibility is a persistent conversation preference', async ({ page }) => {
  await ready(page)
  await send(page, 'timeline approve')
  await expect(page.locator('.tool-card')).toHaveCount(1)
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(page.locator('.transcript .brand')).toHaveCount(0)
  await expect(page.locator('.transcript .message-byline .status-badge')).toBeVisible()
  const scrollLayout = await page.locator('.conversation-scroll').evaluate(element => {
    const scrollRect = element.getBoundingClientRect()
    const composerRect = document.querySelector('.composer-dock')!.getBoundingClientRect()
    return { scrollBottom: scrollRect.bottom, composerTop: composerRect.top, viewportBottom: window.innerHeight }
  })
  expect(scrollLayout.scrollBottom).toBeGreaterThan(scrollLayout.composerTop)
  expect(scrollLayout.scrollBottom).toBeCloseTo(scrollLayout.viewportBottom, 0)

  await page.getByRole('button', { name: 'Hide tool calls', exact: true }).click()
  await expect(page.locator('.tool-card')).toHaveCount(0)
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Show tool calls', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect.poll(async () => page.locator('.conversation-scroll').evaluate(element => element.scrollTop + element.clientHeight >= element.scrollHeight - 1)).toBe(true)

  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Continue with verification?', { exact: true })).toBeVisible()
  await expect(page.locator('.tool-card')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Answer', exact: true }).fill('Continue')
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()

  await page.reload()
  await expect(page.getByRole('button', { name: 'Show tool calls', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  await expect(page.locator('.tool-card')).toHaveCount(0)
  await expect(page.locator('.transcript .message-assistant')).toHaveCount(3)
  await expect(page.locator('.transcript .brand')).toHaveCount(0)
  await expect(page.locator('.transcript .message-byline')).toHaveCount(0)

  await page.getByRole('button', { name: 'Show tool calls', exact: true }).click()
  await expect(page.locator('.tool-card')).toHaveCount(2)
  await expect(page.locator('.transcript .message-assistant')).toHaveCount(3)
})

test('mixed and tool-only history rounds keep tool spacing after refresh without hiding answers', async ({ page }) => {
  await ready(page)
  await send(page, 'tool-only workspace')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Hide tool calls', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Show tool calls', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.tool-card')).toHaveCount(0)
  await expect(page.locator('.transcript .message-assistant:visible')).toHaveCount(2)
  const visibleRoundMargins = await page.locator('.transcript .message-assistant:visible').evaluateAll(messages => messages.map(message => getComputedStyle(message).marginBottom))
  expect(visibleRoundMargins).toEqual(['5px', '5px'])
  await expect(page.locator('.transcript .message-assistant:visible .markdown')).toHaveText(['Checking the workspace before editing.', 'Your workspace is ready. We can take the next step together.'])
  await page.getByRole('button', { name: 'Show tool calls', exact: true }).click()
  await expect(page.locator('.tool-card')).toHaveCount(4)
  await expect(page.locator('.transcript .message-assistant:visible')).toHaveCount(4)
  await expect(page.locator('.message-with-tools')).toHaveCount(3)
  const roundMargins = await page.locator('.message-with-tools').evaluateAll(messages => messages.map(message => getComputedStyle(message).marginBottom))
  expect(roundMargins).toEqual(['5px', '5px', '5px'])
  await expect(page.locator('.message-with-tools:not(:has(.message-content))')).toHaveCount(2)
  const gaps = await page.locator('.transcript .message-assistant .tool-card').evaluateAll(cards => cards.slice(1).map((card, index) => {
    const previous = cards[index].getBoundingClientRect()
    return card.getBoundingClientRect().top - previous.bottom
  }))
  expect(gaps).toHaveLength(3)
  for (const gap of gaps) expect(gap).toBeCloseTo(10, 0)
  await expect(page.locator('.transcript .brand')).toHaveCount(0)
})

test('global request drawer has independent accessible fields and settles inline requests', async ({ page }) => {
  await ready(page)
  await send(page, 'ask from the global drawer')
  await expect(page.getByRole('textbox', { name: 'Answer', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Pending requests', exact: true })
  const input = drawer.getByRole('textbox', { name: 'Answer', exact: true })
  await expect(input).toBeVisible()
  await input.fill('drawer response')
  const ids = await page.locator('.interaction-card textarea').evaluateAll(inputs => inputs.map(input => input.id))
  expect(new Set(ids).size).toBe(ids.length)
  await drawer.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(drawer.getByRole('textbox', { name: 'Answer', exact: true })).toHaveCount(0)
  await drawer.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
})

test('an initially selected complex operation submits the JSON editor contents', async ({ page }) => {
  await page.route('**/api/state', async route => {
    const response = await route.fetch()
    const state = await response.json()
    state.operations = state.operations.filter((item: { name: string }) => item.name === 'complex')
    await route.fulfill({ response, json: state })
  })
  await ready(page)
  await openOperationDebugger(page)
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('{"items":["initial complex input"]}')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  await expect(page.locator('.operation-call').filter({ hasText: 'initial complex input' })).toHaveCount(1)
})

test('cancellation retains partial output and becomes terminal', async ({ page }) => {
  await ready(page)
  await send(page, 'hold workspace')
  await expect(page.getByText('Partial response', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stop execution', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Stop execution', exact: true })).toHaveCount(0)
  await expect(page.getByText('Partial response', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Canceled/ })).toBeVisible()
  await send(page, 'next after cancellation')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  const text = page.locator('.transcript .markdown').filter({ hasText: /^\s*(Partial response|next after cancellation)\s*$/ })
  await expect(text).toHaveText(['Partial response', 'next after cancellation'])
})

test('closing an unchanged slash command cancels its form and a new command can submit', async ({ page }) => {
  await ready(page)
  const composer = page.getByRole('textbox', { name: 'Message your agent…', exact: true })
  await composer.fill('/')
  await page.getByRole('option', { name: /\/tool-shell/ }).click()
  await expect(composer).toHaveValue('/tool-shell ')
  await page.getByRole('option', { name: /config/ }).click()
  const dialog = page.getByRole('dialog', { name: '/tool-shell config', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('textbox', { name: 'Tool', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: /Rules/ }).click()
  await dialog.getByRole('button', { name: /workspace.inspect/ }).click()
  await expect(dialog.getByRole('textbox', { name: 'Tool', exact: true })).toHaveValue('workspace.inspect')
  await expect(dialog.getByRole('button', { name: 'Cancel operation' })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click()
  await expect(dialog).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  const pending = page.getByRole('dialog', { name: 'Pending requests', exact: true })
  await expect(pending.getByText('You’re all caught up.')).toBeVisible()
  await pending.getByRole('button', { name: 'Close', exact: true }).click()
  await composer.fill('/tool-shell config')
  await composer.press('Enter')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: /Rules/ }).click()
  await dialog.getByRole('button', { name: 'Add item', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'Tool', exact: true }).fill('workspace.verify')
  await dialog.getByRole('radio', { name: 'Allow', exact: true }).check()
  await expect(dialog.locator('textarea')).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(dialog.getByText('Operation completed.', { exact: true })).toBeVisible()
  await expect(page).toHaveURL(/#\/new$/)
  await expect(page.locator('.message')).toHaveCount(0)
})

test('closing an edited slash command shelves its draft for later submission', async ({ page }) => {
  await ready(page)
  const composer = page.getByRole('textbox', { name: 'Message your agent…', exact: true })
  await composer.fill('/tool-shell config')
  await composer.press('Enter')
  const dialog = page.getByRole('dialog', { name: '/tool-shell config', exact: true })
  await dialog.getByRole('button', { name: /Rules/ }).click()
  await dialog.getByRole('button', { name: /workspace.inspect/ }).click()
  await dialog.getByRole('textbox', { name: 'Tool', exact: true }).fill('workspace.verify')
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  const pending = page.getByRole('dialog', { name: 'Pending requests', exact: true })
  await expect(pending.getByRole('button', { name: /\/tool-shell config/ })).toBeVisible()
  await pending.getByRole('button', { name: /\/tool-shell config/ }).click()
  await dialog.getByRole('button', { name: /Rules/ }).click()
  await dialog.getByRole('button', { name: /workspace.verify/ }).click()
  await expect(dialog.getByRole('textbox', { name: 'Tool', exact: true })).toHaveValue('workspace.verify')
  await dialog.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(dialog.getByText('Operation completed.', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click()
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Pending requests', exact: true }).getByText('You’re all caught up.')).toBeVisible()
})

test('restoring an edited slash command value leaves no pending request', async ({ page }) => {
  await ready(page)
  const composer = page.getByRole('textbox', { name: 'Message your agent…', exact: true })
  await composer.fill('/tool-shell config')
  await composer.press('Enter')
  const dialog = page.getByRole('dialog', { name: '/tool-shell config', exact: true })
  await dialog.getByRole('button', { name: /Rules/ }).click()
  await dialog.getByRole('button', { name: /workspace.inspect/ }).click()
  const tool = dialog.getByRole('textbox', { name: 'Tool', exact: true })
  await tool.fill('workspace.verify')
  await tool.fill('workspace.inspect')
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Pending requests', exact: true }).getByText('You’re all caught up.')).toBeVisible()
})

test('closing before a slash command starts cancels it when the response arrives', async ({ page }) => {
  let releaseResponse!: () => void
  let operationStarted!: () => void
  const started = new Promise<void>(resolve => { operationStarted = resolve })
  const held = new Promise<void>(resolve => { releaseResponse = resolve })
  await page.route('**/api/operations/*', async route => {
    const response = await route.fetch()
    operationStarted()
    await held
    await route.fulfill({ response })
  })
  await ready(page)
  const composer = page.getByRole('textbox', { name: 'Message your agent…', exact: true })
  await composer.fill('/tool-shell config')
  await composer.press('Enter')
  await started
  await expect.poll(async () => {
    const state = await (await page.request.get('/api/state')).json()
    return state.interactions.length
  }).toBe(1)
  const dialog = page.getByRole('dialog', { name: '/tool-shell config', exact: true })
  await dialog.getByRole('button', { name: 'Close', exact: true }).last().click()
  await expect(dialog).toHaveCount(0)
  releaseResponse()
  await expect.poll(async () => {
    const state = await (await page.request.get('/api/state')).json()
    return state.interactions.length
  }).toBe(0)
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Pending requests' }).getByText('You’re all caught up.')).toBeVisible()
})

test('slash command recovers its form when the event stream stops delivering events', async ({ page }) => {
  await page.addInitScript(() => {
    const nativeFetch = window.fetch.bind(window)
    window.fetch = (input, init) => String(input).startsWith('/api/events?after=')
      ? Promise.resolve(new Response(new ReadableStream(), { headers: { 'Content-Type': 'text/event-stream' } }))
      : nativeFetch(input, init)
  })
  await ready(page)
  const composer = page.getByRole('textbox', { name: 'Message your agent…', exact: true })
  await composer.fill('/tool-shell config')
  await composer.press('Enter')
  const dialog = page.getByRole('dialog', { name: '/tool-shell config', exact: true })
  await expect(dialog.getByRole('button', { name: /Rules/ })).toBeVisible()
  await expect(dialog.getByText('Waiting for operation state…')).toHaveCount(0)
  const canceled = page.waitForResponse(response => response.url().includes('/operation-invocations/') && response.request().method() === 'DELETE')
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click()
  expect((await canceled).ok()).toBe(true)
  await expect(dialog).toHaveCount(0)
})

test('nested providers keep complex detail navigation and edit scalar lists inline', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await ready(page)
  await page.getByRole('textbox', { name: 'Message your agent…', exact: true }).fill('/model-openai-compatible config')
  await page.getByRole('textbox', { name: 'Message your agent…', exact: true }).press('Enter')
  const dialog = page.getByRole('dialog', { name: '/model-openai-compatible config', exact: true })
  await expect(dialog.getByRole('button', { name: /Providers/ })).toBeVisible()
  const width = (await dialog.locator('.field-page').boundingBox())!.width
  await page.screenshot({ path: 'test-results/operation-overview.png' })
  await dialog.getByRole('button', { name: /Providers/ }).click()
  await expect(dialog.getByRole('textbox')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/operation-providers.png' })
  await dialog.getByRole('button', { name: /Example provider/ }).click()
  await expect(dialog.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Example provider')
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('Updated provider')
  await expect(dialog.locator('textarea')).toHaveCount(0)
  expect((await dialog.locator('.field-page').boundingBox())!.width).toBeCloseTo(width, 2)
  await page.screenshot({ path: 'test-results/operation-provider-detail.png' })
  const models = dialog.locator('.field-inline-section').filter({ hasText: 'Models' })
  await models.getByRole('button', { name: 'Add item', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'Item 3', exact: true }).fill('example-new')
  await models.getByRole('button', { name: 'Remove item 1', exact: true }).click()
  await expect(dialog.getByRole('textbox', { name: 'Item 1', exact: true })).toHaveValue('example-reasoner')
  await expect(dialog.getByRole('textbox', { name: 'Item 2', exact: true })).toHaveValue('example-new')
  expect((await dialog.locator('.field-page').boundingBox())!.width).toBeCloseTo(width, 2)
  await page.screenshot({ path: 'test-results/operation-models.png' })

  await dialog.getByRole('button', { name: /Default headers/ }).click()
  await dialog.getByRole('button', { name: /X-Tenant/ }).click()
  await expect(dialog.getByRole('textbox', { name: 'Value', exact: true })).toHaveValue('')
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('X-Renamed')
  await dialog.getByRole('radio', { name: 'Replace', exact: true }).check()
  await dialog.getByRole('textbox', { name: 'Value', exact: true }).fill('new-secret')
  expect((await dialog.locator('.field-page').boundingBox())!.width).toBeCloseTo(width, 2)
  await page.screenshot({ path: 'test-results/operation-header-detail.png' })
  await page.setViewportSize({ width: 360, height: 780 })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(dialog.getByRole('button', { name: 'Submit response', exact: true })).toBeInViewport()
  const valueBox = (await dialog.getByRole('textbox', { name: 'Value', exact: true }).boundingBox())!
  const footerBox = (await dialog.locator('.overlay-footer').boundingBox())!
  expect(valueBox.y + valueBox.height).toBeLessThanOrEqual(footerBox.y)
  await page.screenshot({ path: 'test-results/operation-header-mobile.png' })
  await expect(dialog.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('X-Renamed')
  const response = page.waitForRequest(request => request.url().includes('/response') && request.method() === 'POST')
  await dialog.getByRole('button', { name: 'Submit response', exact: true }).click()
  const body = (await response).postDataJSON()
  expect(JSON.stringify(body)).toContain('Updated provider')
  expect(JSON.stringify(body)).toContain('example-new')
  expect(JSON.stringify(body)).toContain('X-Renamed')
  expect(JSON.stringify(body)).toContain('new-secret')
  expect(JSON.stringify(body)).not.toContain('example-chat')
  await expect(dialog.getByText('Operation completed.', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('operation drilldown works in the debugger and dark Chinese mobile dialog', async ({ page }) => {
  await ready(page)
  await openOperationDebugger(page)
  await page.getByLabel('Select an operation').selectOption({ label: '/model-openai-compatible config' })
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  const call = page.locator('.operation-call').first()
  await call.getByRole('button', { name: /Providers/ }).click()
  await call.getByRole('button', { name: /Example provider/ }).click()
  await expect(call.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Example provider')
  await expect(page.locator('.operations-view textarea')).toHaveCount(0)
  await call.getByRole('button', { name: 'Submit response', exact: true }).click()
  await page.goto('/#/new')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByLabel('Language', { exact: true }).selectOption('zh')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('textbox', { name: '向你的 Agent 发送消息…', exact: true }).fill('/model-openai-compatible config')
  await page.getByRole('textbox', { name: '向你的 Agent 发送消息…', exact: true }).press('Enter')
  const dialog = page.getByRole('dialog', { name: '/model-openai-compatible config', exact: true })
  await dialog.getByRole('button', { name: /Providers/ }).click()
  await dialog.getByRole('button', { name: /Example provider/ }).click()
  await page.screenshot({ path: 'test-results/operation-provider-dark.png' })
  await page.setViewportSize({ width: 360, height: 780 })
  await expect(dialog.getByRole('button', { name: '提交回复', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/operation-provider-dark-mobile.png' })
  await dialog.getByRole('button', { name: '关闭', exact: true }).last().click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: '待处理请求', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '待处理请求' }).getByText('所有请求均已处理。')).toBeVisible()
})

test('session rename, archive, restore, fork and delete', async ({ page }) => {
  await ready(page)
  await send(page, 'session lifecycle')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  const menu = page.locator('.conversation-header').getByRole('button', { name: /^Details:/ })
  await menu.click()
  await page.getByRole('menuitem', { name: 'Rename', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('Browser lifecycle')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser lifecycle', exact: true })).toBeVisible()
  await menu.click()
  await page.getByRole('menuitem', { name: 'Archive', exact: true }).click()
  await expect(page.getByText('This conversation is archived. Restore it to continue.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await menu.click()
  await page.getByRole('menuitem', { name: 'Fork conversation', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('Fork for testing')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Fork for testing', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await expect(page.locator('.session-usage-card').getByTestId('session-total')).toHaveText('0')
  await send(page, 'fork response')
  await expect(page.locator('.session-usage-card').getByTestId('session-total')).toHaveText('72')
  await page.locator('.conversation-header').getByRole('button', { name: /^Details:/ }).click()
  await page.getByRole('menuitem', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page).toHaveURL(/#\/new$/)
})

test('attachment-only upload can be previewed after refreshing', async ({ page }) => {
  await ready(page)
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aO2sAAAAASUVORK5CYII=', 'base64')
  await page.locator('input[type=file]').setInputFiles({ name: 'pixel.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.getByText('Attachment received.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('pixel.png', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.getByRole('img', { name: 'pixel.png', exact: true })).toBeVisible()
})

test('operation form, complex JSON, result recovery, and cancellation', async ({ page }) => {
  await ready(page)
  await openOperationDebugger(page)
  await page.getByLabel('Select an operation', { exact: true }).selectOption({ label: '/test echo' })
  await page.getByLabel('value', { exact: false }).fill('42')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  await expect(page.locator('.operation-call').filter({ hasText: '"value": 42' })).toHaveCount(1)
  await page.reload()
  await expect(page.locator('.operation-call').filter({ hasText: '"value": 42' })).toHaveCount(1)
  await page.getByLabel('Select an operation', { exact: true }).selectOption({ label: '/test complex' })
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('{"items":["one","two"]}')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  // Match this test's own unique input value rather than the broad '"items"'
  // marker. Earlier tests share the same fixture server (workers: 1), so a
  // previous complex invocation would otherwise leave a second matching card.
  await expect(page.locator('.operation-call').filter({ hasText: '"two"' })).toHaveCount(1)
  await page.getByLabel('Select an operation', { exact: true }).selectOption({ label: '/test wait' })
  await page.getByLabel('value', { exact: false }).fill('1')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  const call = page.locator('.operation-call').filter({ has: page.getByText('wait', { exact: true }) })
  await call.getByRole('button', { name: 'Stop execution', exact: true }).click()
  await expect(call.getByText('Canceled', { exact: true })).toBeVisible()
})

test('Run-only capability and execution failure', async ({ page }) => {
  await ready(page, 'http://127.0.0.1:17317')
  await send(page, 'non streaming')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await send(page, 'fail this request')
  await expect(page.getByText('fixture execution failed', { exact: true })).toBeVisible()
})

test('expired SSE cursor bootstraps again without blocking the composer', async ({ page }) => {
  let attempts = 0
  await page.route('**/api/events?*', async route => {
    if (++attempts === 1) await route.fulfill({ status: 409, contentType: 'application/json', body: '{"error":{"code":"event_cursor_expired","message":"Expired"}}' })
    else await route.continue()
  })
  await ready(page)
  await send(page, 'recover connection')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  expect(attempts).toBeGreaterThan(1)
})

test('dark theme, Chinese locale, mobile navigation, and no horizontal overflow', async ({ page }) => {
  await ready(page)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByLabel('Language', { exact: true }).selectOption('zh')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.setViewportSize({ width: 360, height: 780 })
  await page.getByRole('button', { name: '会话', exact: true }).click()
  await expect(page.getByRole('link', { name: /新对话/ }).filter({ visible: true })).toBeVisible()
  await page.getByRole('link', { name: /新对话/ }).filter({ visible: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile-dark-zh.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/desktop-dark-zh.png', fullPage: true })
})
