import { test, expect, type Page } from '@playwright/test'

async function ready(page: Page, base = '') {
  await page.goto(base + '/#/new')
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
}
async function chooseWorkspace(page: Page) {
  const browse = page.getByRole('button', { name: 'Choose workspace folder', exact: true })
  if (await browse.count()) {
    await browse.click()
    await page.getByRole('button', { name: 'Select this folder', exact: true }).click()
  }
}
async function send(page: Page, input: string) {
  await chooseWorkspace(page)
  await page.getByRole('textbox', { name: 'Message your agent…', exact: true }).fill(input)
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page).toHaveURL(/#\/sessions\//)
}

test('conversation creation, streamed output, execution detail, and history refresh', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await ready(page)
  await send(page, 'hello workspace')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await expect(page.getByText('Input tokens', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.message-user .message-content')).toHaveText('hello workspace')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  expect(errors).toEqual([])
})

test('pending approval survives refresh while history is blocked and settles across tabs', async ({ page, context }) => {
  await ready(page)
  await send(page, 'approve workspace')
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(page.getByText('Earlier messages may be available after the current execution finishes.', { exact: true })).toBeVisible()
  const second = await context.newPage()
  await second.goto(page.url())
  await expect(second.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(second.getByText('Allow workspace inspection?', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await second.close()
})

test('free text answers can differ from suggestions', async ({ page }) => {
  await ready(page)
  await send(page, 'ask workspace')
  await page.getByRole('textbox', { name: 'Answer', exact: true }).fill('a different answer')
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
})

test('multi-round reasoning, commentary, tools and interactions append in order', async ({ page }) => {
  await ready(page)
  await send(page, 'timeline approve')
  const timeline = page.locator('.turn-content')
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(timeline.locator(':scope > *')).toHaveClass(['reasoning-block', 'markdown', 'tool-card', 'interaction-card', 'thinking-dots'])
  await timeline.locator('.reasoning-block summary').click()
  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Continue with verification?', { exact: true })).toBeVisible()
  await expect(timeline.locator(':scope > *')).toHaveClass(['reasoning-block', 'markdown', 'tool-card', 'reasoning-block', 'markdown', 'tool-card', 'interaction-card', 'thinking-dots'])
  await expect(timeline.locator('.reasoning-block').first()).toHaveAttribute('open', '')
  await expect(timeline.locator('.reasoning-block .markdown').first()).toHaveText('Checking the request.')
  await timeline.locator('.reasoning-block summary').nth(1).click()
  await expect(timeline.locator('.reasoning-block .markdown').nth(1)).toHaveText('Reviewing the inspection. Planning a verification.')
  await timeline.getByRole('textbox', { name: 'Answer', exact: true }).fill('Continue')
  await timeline.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  const history = page.locator('.transcript .message-assistant .message-content > .markdown, .transcript .tool-summary .font-mono')
  await expect(history).toHaveText(["I'll inspect the workspace first.", 'workspace.inspect', "The first check is complete. I'll verify the result.", 'workspace.verify', 'Your workspace is ready. We can take the next step together.'])
  await page.reload()
  await expect(history).toHaveText(["I'll inspect the workspace first.", 'workspace.inspect', "The first check is complete. I'll verify the result.", 'workspace.verify', 'Your workspace is ready. We can take the next step together.'])
})

test('tool call visibility is a persistent conversation preference', async ({ page }) => {
  await ready(page)
  await send(page, 'timeline approve')
  await expect(page.locator('.tool-card')).toHaveCount(1)
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  const scrollLayout = await page.locator('.conversation-scroll').evaluate(element => {
    const scrollRect = element.getBoundingClientRect()
    const composerRect = document.querySelector('.composer-dock')!.getBoundingClientRect()
    return { scrollBottom: scrollRect.bottom, composerTop: composerRect.top, viewportBottom: window.innerHeight }
  })
  expect(scrollLayout.scrollBottom).toBeGreaterThan(scrollLayout.composerTop)
  expect(scrollLayout.scrollBottom).toBeCloseTo(scrollLayout.viewportBottom, 0)

  await page.getByRole('button', { name: 'Hide tool calls', exact: true }).click()
  await expect(page.locator('.tool-card')).toHaveCount(0)
  await expect(page.getByText('Allow workspace inspection?', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Show tool calls', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect.poll(async () => page.locator('.conversation-scroll').evaluate(element => element.scrollTop + element.clientHeight >= element.scrollHeight - 1)).toBe(true)

  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Continue with verification?', { exact: true })).toBeVisible()
  await expect(page.locator('.tool-card')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Answer', exact: true }).fill('Continue')
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()

  await page.reload()
  await expect(page.getByRole('button', { name: 'Show tool calls', exact: true })).toHaveAttribute('aria-pressed', 'false')
  // await expect(page.locator('.tool-card')).toHaveCount(0)

  await page.getByRole('button', { name: 'Show tool calls', exact: true }).click()
  await expect(page.locator('.tool-card')).toHaveCount(2)
})

test('global request drawer has independent accessible fields and settles inline requests', async ({ page }) => {
  await ready(page)
  await send(page, 'ask from the global drawer')
  await expect(page.getByRole('textbox', { name: 'Answer', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pending requests', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Pending requests', exact: true })
  const input = drawer.getByRole('textbox', { name: 'Answer', exact: true })
  await expect(input).toBeVisible()
  await input.fill('drawer response')
  const ids = await page.locator('.interaction-card textarea').evaluateAll(inputs => inputs.map(input => input.id))
  expect(new Set(ids).size).toBe(ids.length)
  await drawer.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(drawer.getByRole('textbox', { name: 'Answer', exact: true })).toHaveCount(0)
  await drawer.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
})

test('an initially selected complex operation submits the JSON editor contents', async ({ page }) => {
  await page.route('**/api/state', async route => {
    const response = await route.fetch()
    const state = await response.json()
    state.operations = state.operations.filter((item: { name: string }) => item.name === 'complex')
    await route.fulfill({ response, json: state })
  })
  await ready(page)
  await page.getByRole('link', { name: /^Operations/ }).click()
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('{"items":["initial complex input"]}')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  await expect(page.locator('.operation-call').filter({ hasText: 'initial complex input' })).toHaveCount(1)
})

test('cancellation retains partial output and becomes terminal', async ({ page }) => {
  await ready(page)
  await send(page, 'hold workspace')
  await expect(page.getByText('Partial response', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stop execution', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Stop execution', exact: true })).toHaveCount(0)
  await expect(page.getByText('Partial response', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Canceled/ })).toBeVisible()
  await send(page, 'next after cancellation')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  const text = page.locator('.transcript .markdown').filter({ hasText: /^\s*(Partial response|next after cancellation)\s*$/ })
  await expect(text).toHaveText(['Partial response', 'next after cancellation'])
})

test('session rename, archive, restore, fork and delete', async ({ page }) => {
  await ready(page)
  await send(page, 'session lifecycle')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  const menu = page.locator('.conversation-header').getByRole('button', { name: /^Details:/ })
  await menu.click()
  await page.getByRole('menuitem', { name: 'Rename', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('Browser lifecycle')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser lifecycle', exact: true })).toBeVisible()
  await menu.click()
  await page.getByRole('menuitem', { name: 'Archive', exact: true }).click()
  await expect(page.getByText('This conversation is archived. Restore it to continue.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await menu.click()
  await page.getByRole('menuitem', { name: 'Fork conversation', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('Fork for testing')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Fork for testing', exact: true })).toBeVisible()
  await page.locator('.conversation-header').getByRole('button', { name: /^Details:/ }).click()
  await page.getByRole('menuitem', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page).toHaveURL(/#\/new$/)
})

test('attachment-only upload can be previewed after refreshing', async ({ page }) => {
  await ready(page)
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aO2sAAAAASUVORK5CYII=', 'base64')
  await page.locator('input[type=file]').setInputFiles({ name: 'pixel.png', mimeType: 'image/png', buffer: png })
  await chooseWorkspace(page)
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.getByText('Attachment received.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('pixel.png', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.getByRole('img', { name: 'pixel.png', exact: true })).toBeVisible()
})

test('operation form, complex JSON, result recovery, and cancellation', async ({ page }) => {
  await ready(page)
  await page.getByRole('link', { name: /^Operations/ }).click()
  await page.getByLabel('Select an operation', { exact: true }).selectOption('echo')
  await page.getByLabel('value', { exact: false }).fill('42')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  await expect(page.locator('.operation-call').filter({ hasText: '"value": 42' })).toHaveCount(1)
  await page.reload()
  await expect(page.locator('.operation-call').filter({ hasText: '"value": 42' })).toHaveCount(1)
  await page.getByLabel('Select an operation', { exact: true }).selectOption('complex')
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('{"items":["one","two"]}')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  // Match this test's own unique input value rather than the broad '"items"'
  // marker. Earlier tests share the same fixture server (workers: 1), so a
  // previous complex invocation would otherwise leave a second matching card.
  await expect(page.locator('.operation-call').filter({ hasText: '"two"' })).toHaveCount(1)
  await page.getByLabel('Select an operation', { exact: true }).selectOption('wait')
  await page.getByLabel('value', { exact: false }).fill('1')
  await page.getByRole('button', { name: 'Run operation', exact: true }).click()
  const call = page.locator('.operation-call').filter({ hasText: 'wait' })
  await call.getByRole('button', { name: 'Stop execution', exact: true }).click()
  await expect(call.getByText('Canceled', { exact: true })).toBeVisible()
})

test('Run-only capability and execution failure', async ({ page }) => {
  await ready(page, 'http://127.0.0.1:17317')
  await send(page, 'non streaming')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toHaveCount(1)
  await send(page, 'fail this request')
  await expect(page.getByText('fixture execution failed', { exact: true })).toBeVisible()
})

test('expired SSE cursor bootstraps again without blocking the composer', async ({ page }) => {
  let attempts = 0
  await page.route('**/api/events?*', async route => {
    if (++attempts === 1) await route.fulfill({ status: 409, contentType: 'application/json', body: '{"error":{"code":"event_cursor_expired","message":"Expired"}}' })
    else await route.continue()
  })
  await ready(page)
  await send(page, 'recover connection')
  await expect(page.getByText('Your workspace is ready. We can take the next step together.', { exact: true })).toBeVisible()
  expect(attempts).toBeGreaterThan(1)
})

test('dark theme, Chinese locale, mobile navigation, and no horizontal overflow', async ({ page }) => {
  await ready(page)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByLabel('Language', { exact: true }).selectOption('zh')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.setViewportSize({ width: 360, height: 780 })
  await page.getByRole('button', { name: '会话', exact: true }).click()
  await expect(page.getByRole('link', { name: /新对话/ }).filter({ visible: true })).toBeVisible()
  await page.getByRole('link', { name: /新对话/ }).filter({ visible: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile-dark-zh.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/desktop-dark-zh.png', fullPage: true })
})
